# Alacritty Configuration

[window]
dimensions = { columns = 150, lines = 45 }
padding = { x = 10, y = 10 }
decorations = "Full"
dynamic_title = true
startup_mode = "Windowed"

[font]
normal = { family = "FiraCode Nerd Font", style = "Retina" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 16.0

[terminal.shell]
program = "/bin/bash"
args = ["-l"]

[colors.primary]
background = "#fdf6e3"
foreground = "#657b83"

[colors.normal]
black = "#073642"
red = "#dc322f"
green = "#859900"
yellow = "#b58900"
blue = "#268bd2"
magenta = "#d33682"
cyan = "#2aa198"
white = "#eee8d5"

[colors.bright]
black = "#002b36"
red = "#cb4b16"
green = "#586e75"
yellow = "#657b83"
blue = "#839496"
magenta = "#6c71c4"
cyan = "#93a1a1"
white = "#fdf6e3"

[cursor]
unfocused_hollow = true

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[[keyboard.bindings]]
key = "Tab"
mods = "Control"
chars = "\u001Cn"

[[keyboard.bindings]]
key = "Tab"
mods = "Control|Shift"
chars = "\u001Cp"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
chars = "\u001Cc"
